const editor = {
        text: "Texto", paragraph: "Parágrafo simples", heading: "Título {{level}}", sectionHeading: "Título de seção", bulletList: "Lista com marcadores", unorderedList: "Lista não ordenada",
        numberedList: "Lista numerada", orderedList: "Lista ordenada", todoList: "Lista de tarefas", checklist: "Lista de verificação", quote: "Citação", blockquote: "Bloco de citação",
        codeBlock: "Bloco de código", preformatted: "Texto pré-formatado", divider: "Divisor", horizontalRule: "Linha horizontal", image: "Imagem", insertImageUrl: "Inserir URL de imagem",
        table: "Tabela", tableDimensions: "3 × 3 com cabeçalho", blocks: "Blocos", lists: "Listas", media: "Mídia", commands: "Comandos do editor", mentions: "Sugestões de menção",
        noResults: "Nenhum resultado", addBlock: "Adicionar bloco", blockActions: "Ações do bloco", addBlockBelow: "Adicionar bloco abaixo", duplicate: "Duplicar", moveUp: "Mover para cima", moveDown: "Mover para baixo", deleteBlock: "Excluir bloco", turnInto: "Transformar em", currentBlock: "Bloco atual",
        imageCouldNotLoad: "Não foi possível carregar a imagem. Edite a URL para tentar novamente.", addImageUrl: "Adicione uma imagem usando uma URL", editImage: "Editar imagem", imageUrl: "URL da imagem", altText: "Texto alternativo", applyImage: "Aplicar imagem", imageWidth: "Largura da imagem", enterImageUrl: "Digite uma URL de imagem HTTP ou HTTPS.",
        documentContent: "Conteúdo do documento", writeOrSlash: "Escreva algo ou digite ‘/’ para ver os comandos…", writeSomething: "Escreva algo…", bold: "Negrito", italic: "Itálico", strikethrough: "Tachado", inlineCode: "Código em linha", editLink: "Editar link", link: "Link", linkUrl: "URL do link", validLink: "Use um link HTTP, HTTPS ou de e-mail.", apply: "Aplicar", tableActions: "Ações da tabela", addRowAbove: "Adicionar linha acima", addRowBelow: "Adicionar linha abaixo", addColumnBefore: "Adicionar coluna antes", addColumnAfter: "Adicionar coluna depois", toggleHeaderRow: "Alternar linha de cabeçalho", deleteRow: "Excluir linha", deleteColumn: "Excluir coluna", deleteTable: "Excluir tabela",
        editorSuggestions: "Sugestões do editor", noMatchingCommands: "Nenhum comando correspondente", startParagraph: "Começar com um parágrafo simples", addHeading: "Adicionar um título de seção", createSimpleList: "Criar uma lista simples", createNumberedList: "Criar uma lista numerada", trackChecklist: "Acompanhar uma lista de tarefas", highlightQuote: "Destacar uma citação", addFormattedCode: "Adicionar código formatado", separateSections: "Separar seções", textFormatting: "Formatação de texto", headingFormat: "Título", linkAction: "Link", moreFormatting: "Mais formatação", removeLink: "Remover link", saveLink: "Salvar link",
    } as const;

export default editor;
