const issue = {
        newIssue: "Nova tarefa", genericIssue: "Tarefa", title: "Título da tarefa", description: "Descrição", status: "Estado", priority: "Prioridade", assignee: "Responsável",
        category: "Categoria", cycle: "Ciclo", estimate: "Estimativa", createdBy: "Criado por", created: "Criado em", updated: "Atualizado em",
        parent: "Tarefa principal", none: "Nenhum", unassigned: "Sem responsável", noIssues: "Nenhuma tarefa ainda", createFirst: "Crie uma tarefa para começar a acompanhar o trabalho deste projeto.",
        low: "Baixa", medium: "Média", high: "Alta", urgent: "Urgente", backlog: "Fila", inProgress: "Em andamento", done: "Concluída",
        todo: "A fazer", unknownStatus: "Estado desconhecido", unknown: "Desconhecido", noCycle: "Sem ciclo", clearFilters: "Limpar filtros", clearFilter: "Limpar filtro de {{filter}}", allIssues: "Todas as tarefas",
        issueTitle: "Título da tarefa", createStatusFirst: "Crie um estado antes de adicionar uma tarefa.", couldNotLoadIssues: "Não foi possível carregar as tarefas do projeto.",
        noIssuesMatch: "Nenhuma tarefa corresponde a estes filtros", clearOrSearch: "Limpe um filtro ou altere sua busca.", createFirstIssue: "Crie sua primeira tarefa para começar a acompanhar o trabalho deste projeto.",
        label: "Etiqueta", filterTitle: "Filtrar tarefas", filters: "Filtros", all: "Todos",
        display: "Exibição", displayOptions: "Opções de exibição", orderBy: "Ordenar por", groupBy: "Agrupar por", manualOrder: "Ordem manual", recentlyUpdated: "Atualizadas recentemente", issueNumber: "Número da tarefa", noGrouping: "Sem agrupamento", selected: "Selecionado", newIssuePrompt: "O que precisa ser feito?", issueStatusAdded: "A tarefa será adicionada a este estado. Você poderá editar suas propriedades em seguida.", describeWork: "Descreva o trabalho",
        closeIssue: "Fechar tarefa", issueActions: "Ações da tarefa", openFullPage: "Abrir página completa", couldNotCopyContent: "Não foi possível copiar o conteúdo da tarefa", copiedContent: "Conteúdo da tarefa copiado", savingIssue: "Salvando…", savedIssue: "Salvo", unsavedIssue: "Alterações não salvas", describeIssue: "Descreva a tarefa…", saveDescription: "Salvar descrição", updatedAgo: "Atualizada {{time}}", addRelation: "Adicionar relação", addParent: "Adicionar tarefa principal", deleteIssueDescription: "A tarefa “{{title}}” será excluída permanentemente.",
        properties: "Propriedades", savingProperty: "Salvando propriedade…", select: "Selecionar", noLabel: "Sem etiqueta", noEstimate: "Sem estimativa", noParent: "Sem tarefa principal", addCycle: "Adicionar ciclo", addParentIssue: "Adicionar tarefa principal", addLabel: "Adicionar etiqueta", state: "Estado", project: "Projeto", subIssues: "Subtarefas", noDescription: "Sem descrição", emptyComment: "Comentário vazio",
        chooseIssueToRelate: "Escolha uma tarefa para relacionar.", chooseIssueFromProject: "Escolha uma tarefa deste projeto.", couldNotAddRelation: "Não foi possível adicionar a relação.", relations: "Relações", removeRelation: "Remover relação", issueIdentifier: "Identificador da tarefa", relationType: "Tipo de relação", relatedTo: "Relacionada a", blocks: "Bloqueia", blockedBy: "Bloqueada por", duplicateOf: "Duplicada de", add: "Adicionar",
        createdThisIssue: "criou esta tarefa", changedStatus: "alterou o estado", changedPriority: "alterou a prioridade", changedAssignee: "alterou o responsável", changedCategory: "alterou a etiqueta", changedCycle: "alterou o ciclo", changedEstimate: "alterou a estimativa", changedParent: "alterou a tarefa principal", addedRelation: "adicionou uma relação", removedRelation: "removeu uma relação", activity: "Atividade", noneValue: "Nenhum", comments: "Comentários", leaveComment: "Escreva um comentário…", commentAction: "Comentar", couldNotAddComment: "Não foi possível adicionar o comentário.", couldNotDeleteComment: "Não foi possível excluir o comentário.", couldNotUpdateComment: "Não foi possível atualizar o comentário.", loadingIssue: "Carregando tarefa", loadingIssueDetails: "Carregando detalhes da tarefa", issuePanel: "Painel da tarefa", couldNotLoadIssue: "Não foi possível carregar esta tarefa.", couldNotSaveIssue: "Não foi possível salvar a tarefa.",
        copyContent: "Copiar todo o conteúdo da tarefa", copyIdentifier: "Copiar identificador da tarefa", copyIssueLink: "Copiar link da tarefa",
        openIssue: "Abrir tarefa", deleteIssue: "Excluir tarefa", filter: "Filtrar", sort: "Ordenar", searchIssues: "Buscar tarefas", issues: "Visualização de tarefas", list: "Lista", layout: "visualização",
        descriptionPlaceholder: "Adicione uma descrição…", comment: "Comentário", addComment: "Adicione um comentário…",
    } as const;

export default issue;
