const issue = {
        newIssue: "New issue", genericIssue: "Issue", title: "Issue title", description: "Description", status: "Status", priority: "Priority", assignee: "Assignee",
        category: "Category", cycle: "Cycle", estimate: "Estimate", createdBy: "Created by", created: "Created", updated: "Updated",
        parent: "Parent", none: "None", unassigned: "Unassigned", noIssues: "No issues yet", createFirst: "Create an issue to start tracking work in this project.",
        low: "Low", medium: "Medium", high: "High", urgent: "Urgent", backlog: "Backlog", inProgress: "In progress", done: "Done",
        todo: "To do", unknownStatus: "Unknown status", unknown: "Unknown", noCycle: "No cycle", clearFilters: "Clear filters", clearFilter: "Clear {{filter}} filter", allIssues: "All issues",
        issueTitle: "Issue title", createStatusFirst: "Create a status before adding an issue.", couldNotLoadIssues: "Could not load the project issues.",
        noIssuesMatch: "No issues match these filters", clearOrSearch: "Try clearing a filter or changing your search.", createFirstIssue: "Create your first issue to start tracking work in this project.",
        label: "Label", filterTitle: "Filter issues", filters: "Filters", all: "All",
        display: "Display", displayOptions: "Display options", orderBy: "Order by", groupBy: "Group by", manualOrder: "Manual order", recentlyUpdated: "Recently updated", issueNumber: "Issue number", noGrouping: "No grouping", selected: "Selected", newIssuePrompt: "What needs to be done?", issueStatusAdded: "The issue will be added to this status. You can edit its properties next.", describeWork: "Describe the work",
        closeIssue: "Close issue", issueActions: "Issue actions", openFullPage: "Open full page", couldNotCopyContent: "Could not copy issue content", copiedContent: "Copied issue content", savingIssue: "Saving…", savedIssue: "Saved", unsavedIssue: "Unsaved changes", describeIssue: "Describe the issue…", saveDescription: "Save description", updatedAgo: "Updated {{time}}", addRelation: "Add relation", addParent: "Add parent", deleteIssueDescription: "The issue “{{title}}” will be deleted permanently.",
        savingDescription: "Saving description…", descriptionSaved: "Saved", descriptionUnsaved: "Unsaved changes", descriptionOffline: "Offline · changes saved on this device", descriptionSaveFailed: "Could not save description", descriptionConflict: "This description changed elsewhere. Your draft is safe.", useSavedDescription: "Use saved version", createIssueFromDraft: "Create issue from my draft", discussion: "Issue discussion", noActivity: "No activity yet.", noComments: "No comments yet.", loadingActivity: "Loading activity", loadingComments: "Loading comments", couldNotLoadActivity: "Could not load activity.", couldNotLoadComments: "Could not load comments.", edited: "edited", draftCopySuffix: "draft copy",
        properties: "Properties", savingProperty: "Saving property…", select: "Select", noLabel: "No label", noEstimate: "No estimate", noParent: "No parent", addCycle: "Add cycle", addParentIssue: "Add parent issue", addLabel: "Add label", state: "State", project: "Project", subIssues: "Sub-issues", noDescription: "No description", emptyComment: "Empty comment",
        chooseIssueToRelate: "Choose an issue to relate.", chooseIssueFromProject: "Choose an issue from this project.", couldNotAddRelation: "Could not add the relation.", relations: "Relations", removeRelation: "Remove relation", issueIdentifier: "Issue identifier", relationType: "Relation type", relatedTo: "Related to", blocks: "Blocks", blockedBy: "Blocked by", duplicateOf: "Duplicate of", add: "Add",
        createdThisIssue: "created this issue", changedStatus: "changed the status", changedPriority: "changed the priority", changedAssignee: "changed the assignee", changedCategory: "changed the label", changedCycle: "changed the cycle", changedEstimate: "changed the estimate", changedParent: "changed the parent issue", addedRelation: "added a relation", removedRelation: "removed a relation", activity: "Activity", noneValue: "None", comments: "Comments", leaveComment: "Leave a comment…", commentAction: "Comment", couldNotAddComment: "Could not add the comment.", couldNotDeleteComment: "Could not delete the comment.", couldNotUpdateComment: "Could not update the comment.", loadingIssue: "Loading issue", loadingIssueDetails: "Loading issue details", issuePanel: "Issue panel", couldNotLoadIssue: "Could not load this issue.", couldNotSaveIssue: "Could not save the issue.",
        copyContent: "Copy all issue content", copyIdentifier: "Copy issue identifier", copyIssueLink: "Copy issue link",
        openIssue: "Open issue", deleteIssue: "Delete issue", filter: "Filter", sort: "Sort", searchIssues: "Search issues", issues: "Issue layout", list: "List", layout: "layout",
        descriptionPlaceholder: "Add a description…", comment: "Comment", addComment: "Add a comment…",
    } as const;

export default issue;
